Simplify copying skel files for users

diff --git a/install b/install
--- a/install
+++ b/install
@@ -380,19 +380,16 @@ fi
 
 cd /etc/skel
 for USERDIR in /home/*; do
+    USERNAME=$(basename "${USERDIR}")
+    log "Copying skel files for user ${USERNAME}"
     for file in $(find . -type f,l); do
-        FILEDIR="$(dirname "${USERDIR}/${file}")"
-        mkdir -p "${FILEDIR}"
-        chmod 750 "${FILEDIR}"
+        mkdir -p "$(dirname "${USERDIR}/${file}")"
         cp -df "${file}" "${USERDIR}/${file}"
-        chmod 640 "${USERDIR}/${file}"
-        log "$(ls -als "${USERDIR}/${file}" || echo "Error copying ${USERDIR}/${file}")"
-        log "$(ls -als "${USERDIR}/${file}")"
+        log "$(ls -1 "${USERDIR}/${file}" || echo "Error copying ${USERDIR}/${file}")"
     done
     find "${USERDIR}" -type d -exec chmod 0750 \{\} \;
     find "${USERDIR}" -type f -exec chmod 0640 \{\} \;
     chmod -R go-rwx "${USERDIR}/.ssh"
-    USERNAME=$(basename "${USERDIR}")
     chown -R "${USERNAME}":"${USERNAME}" "${USERDIR}"
 done
 
