Also copy base skel files to /root

diff --git a/install b/install
--- a/install
+++ b/install
@@ -318,7 +318,25 @@ apt autoremove -y
 log "Installing packages:"${PACKAGES}
 apt install -y ${PACKAGES}
 
-# TODO remove below
+log "Copying skel files for root user"
+cd "/etc/skel"
+for file in $(find . -type f,l); do
+    mkdir -p "$(dirname "/root/${file}")"
+    cp -df "${file}" "/root/${file}"
+    log "$(ls -1 "/root/${file}" || echo "Error copying /root/${file}")"
+done
+cd "${SCRIPTS_PATH}/configs/base/etc/skel"
+for file in $(find . -type f,l); do
+    mkdir -p "$(dirname "/root/${file}")"
+    cp -df "${file}" "/root/${file}"
+    log "$(ls -1 "/root/${file}" || echo "Error copying /root/${file}")"
+done
+log "Resetting permisions in /root"
+mkdir -p /root/.ssh
+chown -R root:root /root
+find /root -type d -exec chmod 0750 \{\} \;
+find /root -type f -exec chmod 0640 \{\} \;
+chmod -R go-rwx /root/.ssh
 
 for MODULE in base ${SELECTED_MODULES}; do
     if [[ ! -d "${SCRIPTS_PATH}/configs/${MODULE}" ]]; then
@@ -336,20 +354,6 @@ for MODULE in base ${SELECTED_MODULES}; do
         log "$(ls -1 "/${file}" || echo "Error copying /${file}")"
     done
 done
-
-log "Copying skel files for root user"
-cd "${SCRIPTS_PATH}/configs/base/etc/skel"
-for file in $(find . -type f,l); do
-    mkdir -p "$(dirname "/root/${file}")"
-    cp -df "${file}" "/root/${file}"
-    log "$(ls -1 "/root/${file}" || echo "Error copying /root/${file}")"
-done
-log "Resetting permisions in /root"
-mkdir -p /root/.ssh
-chown -R root:root /root
-find /root -type d -exec chmod 0750 \{\} \;
-find /root -type f -exec chmod 0640 \{\} \;
-chmod -R go-rwx /root/.ssh
 
 log "Making everything in /usr/local/bin executable"
 chmod a+rx /usr/local/bin/*
